- name: Instalando pacotes do MariaDB
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - mariadb-server
    - mariadb
    - mysql-connector-python
    ansible_python_interpreter: python3
  when: ansible_facts['distribution'] == "CentOS"


- name: Enable service Mysql, and not touch the state
  service:
    name: mariadb
    enabled: yes
    state: started
  when: ansible_facts['distribution'] == "CentOS"